#!/bin/sh
set -eu

app_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
candle_svg="$app_dir/assets/inochi-candle.svg"
logo_svg="$app_dir/assets/inochi-logo.svg"
output_ts="$app_dir/src/generated/inochi-wordmark.ts"
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

python3 "$app_dir/scripts/update-inochi-burn.py" "$candle_svg"

# Compose the whole wordmark (candle + "nochi" letters) into one SVG so the
# i-to-n spacing is baked into the bitmap instead of depending on how each
# browser applies letter-spacing around an inline image.
CANDLE_SVG="$candle_svg" LOGO_SVG="$logo_svg" WORDMARK_SVG="$tmp_dir/wordmark.svg" \
  python3 - <<'PY'
import os
import re

candle = open(os.environ["CANDLE_SVG"]).read()
logo = open(os.environ["LOGO_SVG"]).read()

x = float(re.search(r'<svg[^>]*viewBox="([-\d.]+) ', candle).group(1))
defs = re.search(r"<defs>.*?</defs>", candle, re.S).group(0)
body, flame = re.findall(r"<path\b.*?/>", candle, re.S)
letters = re.findall(
    r"<path\b.*?/>",
    re.search(r'<g fill="#171717">(.*?)</g>', logo, re.S).group(1),
    re.S,
)
assert len(letters) == 5, "expected the five nochi letter paths"

# The logo's letter outlines are static Geist SemiBold at 1000 units/em with
# the wordmark's -25/gap tracking already baked into their positions; at
# candle viewBox x = 112 they sit exactly as authored, and shifting x slides
# them to tune i-to-n. TRACKING tightens the baked gaps further (0 keeps them
# as authored). Box width: 2773 - 5*TRACKING. Height 1024 = 1em of 1000 above
# the baseline plus 24 of padding so the glyph feet are not flush with the
# bitmap edge.
TEXT_COLOR = "#141413"  # rendered body foreground the live text used
# -webkit-font-smoothing: antialiased drew the live text thinner than the
# outlines' geometric coverage. Eroding each glyph edge by THINNING/2 units
# (white fill + black stroke inside a mask) matches that optical weight while
# keeping the ink at full color.
THINNING = 0
TRACKING = 0
n_shift = x - 112
width = 2773 - 5 * TRACKING

shifted = "".join(
    f'<g transform="translate({n_shift - TRACKING * k:g} 0)">{letter}</g>'
    for k, letter in enumerate(letters)
)
nochi_mask = (
    f'<mask id="nochi" maskUnits="userSpaceOnUse" x="{x:g}" y="-240" '
    f'width="{width:g}" height="1024">'
    f'<g fill="#fff" stroke="#000" stroke-width="{THINNING:g}">{shifted}</g>'
    "</mask>"
)
parts = [
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x:g} -240 {width:g} 1024">',
    defs.replace("</defs>", nochi_mask + "</defs>"),
    body,
    flame,
    f'<rect x="{x:g}" y="-240" width="{width:g}" height="1024" '
    f'fill="{TEXT_COLOR}" mask="url(#nochi)"/>',
    "</svg>",
]
open(os.environ["WORDMARK_SVG"], "w").write("\n".join(parts))
PY

if command -v vips >/dev/null 2>&1; then
  vips thumbnail "$tmp_dir/wordmark.svg" "$tmp_dir/wordmark.png" 1536
elif command -v bun >/dev/null 2>&1; then
  # librsvg maps viewBox units 1:1 to px at 72dpi; pick the density that
  # renders the target width directly so no resampling pass is needed.
  svg_width=$(sed -n 's/.*viewBox="[^ ]* [^ ]* \([^ ]*\) .*/\1/p' "$tmp_dir/wordmark.svg")
  WORDMARK_DENSITY=$(awk "BEGIN { print 72 * 1536 / $svg_width }") \
    WORDMARK_PNG="$tmp_dir/wordmark.png" WORDMARK_SOURCE="$tmp_dir/wordmark.svg" bun -e '
    await require("sharp")(process.env.WORDMARK_SOURCE, {
      density: Number(process.env.WORDMARK_DENSITY),
    })
      .resize({ width: 1536 })
      .png()
      .toFile(process.env.WORDMARK_PNG);
  '
else
  echo "vips is required to rasterize the wordmark SVG" >&2
  exit 1
fi
avifenc -s 0 -d 10 -q 85 --qalpha 95 "$tmp_dir/wordmark.png" "$tmp_dir/wordmark.avif"

if base64 --help 2>&1 | grep -q -- '-w'; then
  encoded=$(base64 -w 0 "$tmp_dir/wordmark.avif")
else
  encoded=$(base64 < "$tmp_dir/wordmark.avif" | tr -d '\n')
fi

mkdir -p "$(dirname -- "$output_ts")"
{
  echo '/* Generated by scripts/generate-inochi-wordmark.sh. Do not edit. */'
  printf 'export const INOCHI_WORDMARK_AVIF = "data:image/avif;base64,%s";\n' "$encoded"
} > "$output_ts"
