#!/bin/sh
set -eu

app_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
source_svg="$app_dir/assets/inochi-candle.svg"
output_ts="$app_dir/src/generated/inochi-candle.ts"
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

python3 "$app_dir/scripts/update-inochi-burn.py" "$source_svg"
cp "$source_svg" "$tmp_dir/candle.svg"

if command -v vips >/dev/null 2>&1; then
  vips thumbnail "$tmp_dir/candle.svg" "$tmp_dir/candle.png" 512
elif command -v bun >/dev/null 2>&1; then
  CANDLE_SOURCE="$tmp_dir/candle.svg" CANDLE_PNG="$tmp_dir/candle.png" bun -e '
    await require("sharp")(process.env.CANDLE_SOURCE)
      .resize({ width: 512 })
      .png()
      .toFile(process.env.CANDLE_PNG);
  '
else
  echo "vips is required to rasterize the candle SVG" >&2
  exit 1
fi
avifenc -s 0 -d 10 "$tmp_dir/candle.png" "$tmp_dir/candle.avif"

if base64 --help 2>&1 | grep -q -- '-w'; then
  encoded=$(base64 -w 0 "$tmp_dir/candle.avif")
else
  encoded=$(base64 < "$tmp_dir/candle.avif" | tr -d '\n')
fi

mkdir -p "$(dirname -- "$output_ts")"
{
  echo '/* Generated by scripts/generate-inochi-candle.sh. Do not edit. */'
  printf 'export const INOCHI_CANDLE_AVIF = "data:image/avif;base64,%s";\n' "$encoded"
} > "$output_ts"
